# 추후에 Vault by HashiCorp open source 이용해서 보관 및 사용
EMAIL_USERNAME: apdh1709@gmail.com
EMAIL_PASSWORD: zkuxcbrobzdgkjev

# 아래 환경은 배포시에 aws ec2 환경 변수 입니다.
# 로컬 개발환경에서는 각자 환경에 맞게 변경해서 사용하도록 합니다.
DB_HOST: 172.31.46.10
DB_PORT: 3395
DB_USERNAME: zerobnb
DB_PASSWORD: zerobnb
DB_SCHEMA: zerobnb_mysql

REDIS_HOST: 172.31.46.10
REDIS_PORT: 6500