server:
  servlet:
    session:
      timeout: 60m
  port: 8000

spring:
  thymeleaf:
    cache: false

  devtools:
    livereload:
      enabled: true

    remote:
      restart:
        enabled: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:{port}/{database_name}?profileSQL=true&logger=Slf4JLogger&maxQuerySizeToLog=999999&rewriteBatchedStatements=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: {username}
      password: {password}

  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      format_sql: true
      show_sql: true
      use_sql_comments: true
      ddl-auto: create-drop
      use-new-id-generator-mappings: true
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 10000
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
  sql:
    init:
      mode: always

springdoc:
  cache:
    disabled: true
  swagger-ui:
    path: swagger-ui-custom.html
  api-docs:
    path: /api-docs
  packages-to-scan: com.service.zerobnb

logging:
  pattern:
    console: "[%d] %-5level [${PID:-} - %thread - {%C => %M, %l}] %logger : %msg%n"
    file: "[%d] %-5level [${PID:-} - %thread - {%C => %M, %l}] %logger : %msg%n"

  file:
    name: ./logs/ZeroBnb.log
    max-history: 30

  level:
    root: INFO
    com.service: INFO

    org.hibernate:
      SQL: debug
      type.descriptor.sql: trace

mybatis:
  mapper-locations: mybatis/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl