server:
  servlet:
    session:
      timeout: 60m
  port: 8000

spring:
  thymeleaf:
    cache: false

  devtools:
    livereload:
      enabled: true

    remote:
      restart:
        enabled: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    hikari:
      username: sa
      password:

  jpa:
    defer-datasource-initialization: true
    hibernate:
      format_sql: true
      show_sql: true
      use_sql_comments: true
      ddl-auto: create-drop
      use-new-id-generator-mappings: true
    open-in-view: false

  sql:
    init:
      mode: always

springdoc:
  cache:
    disabled: true
  swagger-ui:
    path: swagger-ui-custom.html
  api-docs:
    path: /api-docs
  packages-to-scan: com.service.zerobnb

logging:
  pattern:
    console: "[%d] %-5level [${PID:-} - %thread - {%C => %M, %l}] %logger : %msg%n"
    file: "[%d] %-5level [${PID:-} - %thread - {%C => %M, %l}] %logger : %msg%n"

  file:
    name: ./logs/ZeroBnb.log
    max-history: 30

  level:
    root: INFO
    com.service: INFO

    org.hibernate:
      SQL: debug
      type.descriptor.sql: trace

mybatis:
  mapper-locations: mybatis/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl