EMAIL_USERNAME: apdh1709@gmail.com
EMAIL_PASSWORD: test

DB_HOST: 172.31.46.10
DB_PORT: 3395
DB_USERNAME: zerobnb
DB_PASSWORD: zerobnb
DB_SCHEMA: zerobnb_mysql

REDIS_HOST: 172.31.46.10
REDIS_PORT: 6500